### ISSUE TITLE
24bit integer wav not properly scaled

### ISSUE THREAD

**Issue by jmyhrman** [TheBerkin/creak#1]
When reading 24bit integer .wav data, the volume gets very low due to how the data is scaled when converted to f32.

Had a quick glance, and I would assume the problem is on this line, where the scaling assumes 32bit integer range rather than 24bit integer range:
https://github.com/TheBerkin/creak/blob/2e88c9936eebd5ac5127ec922b29f977aa4f23bf/src/decoder/wav.rs#L58

**Comment by TheBerkin** [comment]
Whoops! Thanks for pointing this out. I'll get it fixed ASAP.

**Comment by TheBerkin** [comment]
Fixed by 02859041dc8bab2b5dbeebb16595d3d69a666058
